# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments
highlighter: true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Your Name
tagline:          'Ph.D. Student'
description:      'Ph.D. Student'
#url:              http://hyde.getpoole.com
url:               http://p-zhang.github.io
baseurl:          /

author:
  name:           'Your Name'
#  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.1.0

github:
  #repo:           https://github.com/poole/hyde
