# Dependencies
markdown:         kramdown #redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge
#highlighter: pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Peng Zhang
tagline:          'Scientist @ Institute for Infocomm Research'
description:      'Scientist @ Institute for Infocomm Research'
#url:              http://hyde.getpoole.com
url:               http://p-zhang.github.io
baseurl:          /

author:
  name:           'Peng Zhang'
#  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.1.0

github:
  #repo:           https://github.com/poole/hyde
# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

